__author__ = 'zero'

mappingGuiFile = {
    'rbDatabase': 'USE_DATA_FROM_DB',
    'rbFile': 'USE_DATA_FROM_DB',
    'fieldServer': 'DB_SERVER',
    'fieldUser': 'DB_USER',
    'fieldPassword': 'DB_PASSWORD',
    'fieldDatabase': 'DB_DATABASE',
    'fieldCosts': 'TABLE_COSTS',
    'fieldCompatibility' :'TABLE_COMPAT',
    'fieldCover': 'TABLE_COVER',
    'fieldCovertion': 'TABLE_CONVERTION_ELEMENT_ITEM',
    'fieldCost': 'FIELD_COST',
    'fieldCover_2': 'FIELD_COVER',
    'fieldPrimary': 'FIELD_PRIMARY',
    'fieldIDescription': 'FIELD_PRIMARY_DESCRIPTION',
    'fieldElement': 'FIELD_ELEMENT',
    'fieldItem': 'FIELD_ITEM',
    'fieldItem1': 'FIELD_ITEM_COMPAT1',
    'fieldItem2': 'FIELD_ITEM_COMPAT2',
    'fieldSimilarity': 'FIELD_COMPAT',
    'fieldNumFlakes': 'NUM_FLAKES',
    'fieldMaxTrials': 'MAX_TRIALS',
    'fieldBudget': 'BUDGET',
    'fieldToProduce': 'TO_PRODUCE',
    'comboSolver': 'SOLVER',
    'fieldGamma': 'INTER_SIMILARITY_WEIGHT',
    'comboRankingStrategy': 'RANKING_STRATEGY',
    'checkSpecific': 'WITH_SPECIFIC_ITEM',
    'fieldSpecificItem': 'SPECIFIC_ITEM',
    'checkWriteFile': 'WRITE_FILE',
    'checkShowSolution': 'PRINT_TO_SCREEN',
    'fileCosts': 'FILE_COSTS',
    'fileCompat': 'FILE_COMPAT',
    'fileCover': 'FILE_COVER',
    'fileName': 'FILE_NODE_NAME',
    'fileType': 'FILE_TYPE_NAME',
    'fieldDirectory': 'DIRECTORY_WORK'
}